font_family Agave Nerd Font Mono Regular
font_size 16
initial_window_height 1080
initial_window_width 1920
remember_window_size no
background_opacity 0.9
background_image /home/arkboi/Desktop/wallpaper.jpg
background #222330
foreground #cef3ff
cursor #ffffff
selection_background #44475a
color0 #000000
color8 #1c1c1c
color1 #fa0074
color9 #fa0074
color2 #ff5555
color10 #ff5555
color3 #7f0a1f
color11 #7f0a1f
color4 #3282ff
color12 #3282ff
color5 #1b3cff
color13 #1b3cff
color6 #0037fc
color14 #0037fc
color7 #bbbbbb
color15 #bbbbbb
selection_foreground #222330
