font_family Agave Nerd Font Mono Regular
font_size 16
initial_window_height 1080
initial_window_width 1920
remember_window_size no
background_opacity 0.9
background_image /home/arkboi/Desktop/wallpaper.jpg
background #222330
foreground #cef3ff
cursor #ffffff
selection_background #44475a
color0 #000000
color8 #1c1c1c
color1 #ff479d
color9 #ff479d
color2 #fa0074
color10 #fa0074
color3 #eb4034
color11 #eb4034
color4 #3282ff
color12 #3282ff
color5 #1a81e8
color13 #1a81e8
color6 #007ede
color14 #007ede
color7 #bbbbbb
color15 #bbbbbb
selection_foreground #222330
