#!/bin/bash

# Display the date and month
echo "<span size='xx-large' weight='bold'>$(date "+%d %B")</span>"
echo ""

# Output the cheatsheet content
echo "<span color='#268bd2' size='large' weight='bold'>Welcome, Arkboi!</span>"
echo "<span color='#dc322f' size='medium'>What is your focus for today?</span>"
echo "<span color='#b58900' size='medium' underline='single'>Variables</span>"
echo "<span>S - Super, Windows</span>"
echo "<span>M - Alt, Meta</span>"
echo "<span>C - Ctrl</span>"
echo "<span>SH - Shift</span>"
echo "<span>SPC - Space</span>"
echo "<span color='#b58900' size='medium' underline='single'>Keybindings</span>"
echo "<span color='#93a1a1'>S + Enter -</span><span color='#839496'> Terminal (kitty)</span>"
echo "<span color='#93a1a1'>S + SPC -</span><span color='#839496'> App Launcher (rofi)</span>"
echo "<span color='#93a1a1'>S + m -</span><span color='#839496'> Exit Hyprland</span>"
echo "<span color='#93a1a1'>S + d -</span><span color='#839496'> Emoji Picker</span>"
echo "<span color='#93a1a1'>S + SH + Arrow -</span><span color='#839496'> Move Windows</span>"
echo "<span color='#93a1a1'>S + M + Arrow -</span><span color='#839496'> Resize Windows</span>"
echo "<span color='#93a1a1'>S + U I O P -</span><span color='#839496'> Move Focus</span>"
echo "<span color='#93a1a1'>S + [Num] -</span><span color='#839496'> Change Workspace</span>"
echo "<span color='#93a1a1'>S + s -</span><span color='#839496'> Scratchpad</span>"
echo "<span color='#93a1a1'>S + SH + s -</span><span color='#839496'> Move to Scratchpad</span>"
echo "<span color='#93a1a1'>S + w -</span><span color='#839496'> Close Window</span>"
echo "<span color='#93a1a1'>S + c -</span><span color='#839496'> Wallpaper Picker</span>"
echo "<span color='#93a1a1'>S + v -</span><span color='#839496'> Clipboard</span>"
echo "<span color='#b58900' size='medium' underline='single'>Applications</span>"
echo "<span color='#93a1a1'>Terminal -</span><span color='#839496'> Kitty</span>"
echo "<span color='#93a1a1'>File Manager -</span><span color='#839496'> Nemo</span>"
echo "<span color='#93a1a1'>Browser -</span><span color='#839496'> Firefox</span>"
echo "<span color='#93a1a1'>App Launcher -</span><span color='#839496'> Rofi</span>"
echo "<span color='#93a1a1'>Top Bar -</span><span color='#839496'> Waybar</span>"
echo "<span color='#93a1a1'>Text Editor -</span><span color='#839496'> DOOM Emacs</span>"
