#!/bin/bash

# Path to the wal.sh script
wal_dir="$HOME/arkscripts/wal.sh"
reload="$HOME/arkscripts/reload.sh"


# Get the list of themes from the paste.txt file and add the autogenerated option
themes=("autogenerated-from-wallpaper" "blazer" "catppuccin-mocha" "alucard" "3024-dark" "3024-light" "ashes-dark" "ashes-light" "base16-3024" "base16-apathy" "base16-ashes"
"base16-atelier-cave-dark" "base16-atelier-cave-light" "base16-atelier-dune-dark" "base16-atelier-dune-light"
"base16-atelier-estuary-dark" "base16-atelier-estuary-light" "base16-atelier-forest-dark" "base16-atelier-forest-light"
"base16-atelier-heath-dark" "base16-atelier-heath-light" "base16-atelier-lakeside-dark" "base16-atelier-lakeside-light"
"base16-atelier-plateau-dark" "base16-atelier-plateau-light" "base16-atelier-savanna-dark" "base16-atelier-savanna-light"
"base16-atelier-seaside-dark" "base16-atelier-seaside-light" "base16-atelier-sulphurpool-dark" "base16-atelier-sulphurpool-light"
"base16-bespin" "base16-black-metal" "base16-black-metal-bathory" "base16-black-metal-burzum" "base16-black-metal-funeral"
"base16-black-metal-gorgoroth" "base16-black-metal-immortal" "base16-black-metal-khold" "base16-black-metal-marduk"
"base16-black-metal-mayhem" "base16-black-metal-nile" "base16-black-metal-venom" "base16-brewer" "base16-bright"
"base16-brushtrees" "base16-chalk" "base16-circus" "base16-classic-dark" "base16-classic-light" "base16-codeschool"
"base16-cupcake" "base16-cupertino" "base16-default-dark" "base16-default-light" "base16-dracula" "base16-eighties"
"base16-embers" "base16-flat" "base16-github" "base16-google-dark" "base16-google-light" "base16-grayscale-dark"
"base16-grayscale-light" "base16-greenscreen" "base16-gruvbox-hard-dark" "base16-gruvbox-hard-light"
"base16-gruvbox-medium-dark" "base16-gruvbox-medium-light" "base16-gruvbox-pale" "base16-gruvbox-soft-dark"
"base16-gruvbox-soft-light" "base16-harmonic-dark" "base16-harmonic-light" "base16-hopscotch" "base16-icy"
"base16-irblack" "base16-isotope" "base16-macintosh" "base16-marrakesh" "base16-materia" "base16-material"
"base16-material-palenight" "base16-materialer-dark" "base16-materialer-light" "base16-mellow-purple" "base16-mexico"
"base16-mocha" "base16-monokai" "base16-nord" "base16-ocean" "base16-oceanicnext" "base16-one" "base16-onedark"
"base16-outrun" "base16-paraiso" "base16-phd" "base16-pico" "base16-pop" "base16-porple" "base16-railscasts"
"base16-rebecca" "base16-seti" "base16-shapeshifter" "base16-snazzy" "base16-solarflare" "base16-solarized-dark"
"base16-solarized-light" "base16-spacemacs" "base16-summerfruit-dark" "base16-summerfruit-light" "base16-tomorrow"
"base16-tomorrow-night" "base16-tube" "base16-twilight" "base16-unikitty-dark" "base16-unikitty-light" "base16-woodland"
"base16-xcode-dusk" "base16-zenburn" "base16tooth" "darktooth" "dkeg-5725" "dkeg-amiox" "dkeg-bark" "dkeg-blend"
"dkeg-blok" "dkeg-bluetype" "dkeg-blumune" "dkeg-book" "dkeg-branch" "dkeg-brownstone" "dkeg-bulb" "dkeg-chaires"
"dkeg-coco" "dkeg-corduroy" "dkeg-depth" "dkeg-designr" "dkeg-diner" "dkeg-escen" "dkeg-fendr" "dkeg-flapr"
"dkeg-forst" "dkeg-fury" "dkeg-harbing" "dkeg-kit" "dkeg-leaf" "dkeg-link" "dkeg-mattd" "dkeg-novmbr" "dkeg-owl"
"dkeg-paints" "dkeg-parkd" "dkeg-pastely" "dkeg-petal" "dkeg-poly" "dkeg-prevail" "dkeg-provrb" "dkeg-raild"
"dkeg-relax" "dkeg-scag" "dkeg-scape" "dkeg-shade" "dkeg-simplicity" "dkeg-skigh" "dkeg-slate" "dkeg-soundwave"
"dkeg-spire" "dkeg-sprout" "dkeg-squares" "dkeg-stv" "dkeg-subtle" "dkeg-sundr" "dkeg-tealights" "dkeg-traffic"
"dkeg-transposet" "dkeg-urban" "dkeg-vans" "dkeg-victory" "dkeg-view" "dkeg-wintry" "github" "gruvbox"
"hybrid-material" "monokai" "rose-pine" "rose-pine-dawn" "rose-pine-moon" "sexy-astromouse" "sexy-belge"
"sexy-bitmute" "sexy-cloud" "sexy-colorfulcolors" "sexy-dawn" "sexy-deafened" "sexy-derp" "sexy-digerati"
"sexy-doomicideocean" "sexy-dotshare" "sexy-dwmrob" "sexy-eqie6" "sexy-euphrasia" "sexy-gjm" "sexy-gnometerm"
"sexy-gotham" "sexy-gslob-nature-suede" "sexy-hund" "sexy-hybrid" "sexy-insignificato" "sexy-invisibone"
"sexy-jasonwryan" "sexy-kasugano" "sexy-material" "sexy-mikado" "sexy-mikazuki" "sexy-monokai" "sexy-mostly-bright"
"sexy-muse" "sexy-nancy" "sexy-navy-and-ivory" "sexy-neon" "sexy-numixdarkest" "sexy-orangish" "sexy-parker_brothers"
"sexy-phrak1" "sexy-pretty-and-pastel" "sexy-rasi" "sexy-rezza" "sexy-rydgel" "sexy-s3r0-modified" "sexy-sexcolors"
"sexy-simple_rainbow" "sexy-splurge" "sexy-swayr" "sexy-sweetlove" "sexy-tango" "sexy-tangoesque" "sexy-tartan"
"sexy-theme2" "sexy-thwump" "sexy-tlh" "sexy-trim-yer-beard" "sexy-vacuous2" "sexy-visibone" "solarized-dark"
"solarized-light" "srcery" "tempus_autumn" "vscode" "zenburn")

# Display theme options in rofi and get the selected theme
selected=$(printf '%s\n' "${themes[@]}" | rofi -dmenu -i -p "Select Theme:")

# If user cancels, exit
if [ -z "$selected" ]; then
    echo "No theme selected. Exiting."
    exit 1
fi

# Check if the wal.sh file exists
if [ ! -f "$wal_dir" ]; then
    echo "Error: $wal_dir does not exist."
    exit 1
fi

# Replace the wallust theme line in the wal.sh file
if [ "$selected" = "autogenerated-from-wallpaper" ]; then
    # For autogenerated option, use wallust run command
    sed -i '/^wallust/c\wallust pywal -i "$SELECTED_WALL"' "$wal_dir"
    echo "Theme set to autogenerate from wallpaper"
else
    # For regular themes, use wallust theme command
    sed -i '/^wallust/c\wallust cs '"$selected" "$wal_dir"
    echo "Theme updated to: $selected"
fi

# Optional: Execute the wal.sh script to apply the theme immediately
bash "$wal_dir"
bash "$reload"

exit 0
